/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Brain.gltf 
Author: issamchong (https://sketchfab.com/issamchong)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/brain-d1f7e644471d43509c1ce41bce0ec44f
Title: Brain
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Brain(props) {
  const { nodes, materials } = useGLTF('/Brain.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.MALE_F_1Nervous_Pituarty_Gland_GeoSG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.MALE_F_1Nervous_Pituarty_Gland_GeoSG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.MALE_F_1Nervous_Pituarty_Gland_GeoSG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.MALE_F_1Nervous_Pituarty_Gland_GeoSG} />
      </group>
    </group>
  )
}

export default Brain;