/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Circulatory.gltf 
Author: issamchong (https://sketchfab.com/issamchong)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/circulatory-89baee664c1d4464be26888e1dade299
Title: Circulatory
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Circulatory(props) {
  const { nodes, materials } = useGLTF('/Circulatory.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.MALE_F_1Circulatory_Heart_GeoSG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.MALE_F_1Circulatory_Heart_Left_Atrium_GeoSG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.MALE_F_1Circulatory_Heart_Right_Atrium_GeoSG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.MALE_F_1Circulatory_Arteries_GeoSG} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.MALE_F_1Circulatory_Arteries_GeoSG} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.MALE_F_1Circulatory_Bicuspid_Valve_GeoSG} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.MALE_F_1Circulatory_Veins_GeoSG} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.MALE_F_1Circulatory_Veins_GeoSG} />
      </group>
    </group>
  )
}

export default Circulatory;