/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 gallbladder.gltf 
Author: funnyeducomics (https://sketchfab.com/funnyeducomics)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gallbladder-18e0ad1f84bb4eed955148e80b6e1c33
Title: Gallbladder
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Gallbladder(props) {
  const { nodes, materials } = useGLTF('/gallbladder.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.MALE_F_1Digestive_Gall_Bladder_GeoSG} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

export default Gallbladder;