/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 LargeSmall_intestines.gltf 
Author: funnyeducomics (https://sketchfab.com/funnyeducomics)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/large-small-intestines-cf09a181c9ba4a218ceadf2ceb2b15b2
Title: Large& Small_intestines
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LargeSmall_intestines(props) {
  const { nodes, materials } = useGLTF('/LargeSmall_intestines.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.MALE_F_1Digestive_Colon_GeoSG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.MALE_F_1Digestive_Small_Intestine_GeoSG} />
      </group>
    </group>
  )
}

export default LargeSmall_intestines;