/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Muscles.gltf 
Author: issamchong (https://sketchfab.com/issamchong)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/muscles-fbx-0dddf91a33be42e1aa10a6828186e7eb
Title: muscles_fbx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Muscles(props) {
  const { nodes, materials } = useGLTF('/Muscles.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-80, 82.536, 1.711]} rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[0, 0.38, 4.917]}>
            <group position={[0, 1.331, -87.453]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.MALE_F_1Arm_MusclesAbductor_Digiti_Quinti_Brevis_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesAbductor_Digiti_Quinti_Brevis_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesAbductor_Pollicis_Brevis_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesAbductor_Pollicis_Brevis_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesAbductor_Pollicis_Longus_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesAbductor_Pollicis_Longus_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesAdductor_Pollicis_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesAdductor_Pollicis_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesBiceps_Brachii_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesBiceps_Brachii_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesBiceps_Brachii_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesBiceps_Brachii_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesBrachioradialis_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesBrachioradialis_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesCoracobrachialis_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesCoracobrachialis_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesDeltoideus_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesDeltoideus_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesDorsal_Interossei_Muscle_Left_1_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesDorsal_Interossei_Muscle_Left_2_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesDorsal_Interossei_Muscle_Left_3_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesDorsal_Interossei_Muscle_Left_4_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesDorsal_Interossei_Muscle_Left_5_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesDorsal_Interossei_Muscle_Left_6_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesDorsal_Interossei_Muscle_Left_7_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesDorsal_Interossei_Muscle_Right_1_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesDorsal_Interossei_Muscle_Right_2_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesDorsal_Interossei_Muscle_Right_3_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesDorsal_Interossei_Muscle_Right_4_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesDorsal_Interossei_Muscle_Right_5_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesDorsal_Interossei_Muscle_Right_6_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesDorsal_Interossei_Muscle_Right_7_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesExtensor_Carpi_Radialis_Brevis_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesExtensor_Carpi_Radialis_Brevis_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesExtensor_Carpi_Radialis_Longus_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesExtensor_Carpi_Radialis_Longus_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesExtensor_Carpi_Ulnaris_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesExtensor_Carpi_Ulnaris_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesExtensor_Digitorum_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesExtensor_Digitorum_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesExtensor_Indicis_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesExtensor_Indicis_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesExtensor_Pollicis_Brevis_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesExtensor_Pollicis_Brevis_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesExtensor_Pollicis_Longus_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesExtensor_Pollicis_Longus_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesFlexor_Carpi_Radialis_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesFlexor_Carpi_Radialis_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesFlexor_Carpi_Ulnaris_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesFlexor_Carpi_Ulnaris_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesFlexor_Digiti_Quinti_Brevis_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesFlexor_Digiti_Quinti_Brevis_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesFlexor_Digitorum_Profundus_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesFlexor_Digitorum_Profundus_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesFlexor_Digitorum_Superficialis_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesFlexor_Digitorum_Superficialis_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesFlexor_Pollicis_Brevis_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesFlexor_Pollicis_Brevis_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesFlexor_Pollicis_Longus_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesFlexor_Pollicis_Longus_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesLummbrical_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesLummbrical_Muscle_Left1_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesLummbrical_Muscle_Left2_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesLummbrical_Muscle_Left3_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesLummbrical_Muscle_Left4_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesLummbrical_Muscle_Left5_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesLummbrical_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesLummbrical_Muscle_Right1_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesLummbrical_Muscle_Right2_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesLummbrical_Muscle_Right3_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesLummbrical_Muscle_Right4_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesLummbrical_Muscle_Right5_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesOpponens_Digiti_Quinti_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesOpponens_Digiti_Quinti_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesOpponens_Pollicis_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesOpponens_Pollicis_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesPalmar_Interossei_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesPalmar_Interossei_Muscle_Left1_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesPalmar_Interossei_Muscle_Left2_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesPalmar_Interossei_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesPalmar_Interossei_Muscle_Right1_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesPalmar_Interossei_Muscle_Right2_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesPalmaris_Longus_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesPalmaris_Longus_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesPronator_Quadratus_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesPronator_Quadratus_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesPronator_Teres_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesPronator_Teres_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesTricep_Mucsle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesTricep_Mucsle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesTricep_Muscle_Left_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
              <mesh geometry={nodes.MALE_F_1Arm_MusclesTricep_Muscle_Right_MALE_F_1Muscle_Arm_mat_0.geometry} material={materials.MALE_F_1Muscle_Arm_mat} />
            </group>
            <group position={[0, 1.331, -87.453]}>
              <mesh geometry={nodes.MALE_F_1Muscular_EyesNervous_Eye_Ball_Inner_Left_Geo_MALE_F_1Muscular_Eye_Ball_Inner_mat_0.geometry} material={materials.MALE_F_1Muscular_Eye_Ball_Inner_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Muscular_EyesNervous_Eye_Ball_Inner_Right_Geo_MALE_F_1Muscular_Eye_Ball_Inner_mat_0.geometry} material={materials.MALE_F_1Muscular_Eye_Ball_Inner_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Muscular_EyesNervous_Eye_Ball_Outer_Left_Geo_MALE_F_1Muscular_Eye_Ball_Outer_mat_0.geometry} material={materials.MALE_F_1Muscular_Eye_Ball_Outer_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Muscular_EyesNervous_Eye_Ball_Outer_Right_Geo_MALE_F_1Muscular_Eye_Ball_Outer_mat_0.geometry} material={materials.MALE_F_1Muscular_Eye_Ball_Outer_mat} rotation={[Math.PI / 2, 0, 0]} />
            </group>
            <group position={[0, 1.331, -87.453]}>
              <mesh geometry={nodes.MALE_F_1Head_MusclesAuricular_Anterior_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesAuricular_Anterior_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesBuccinator_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesBuccinator_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesCorrugator_Supercilii_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesCorrugator_Supercilii_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesDepressor_Anguli_Oris_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesDepressor_Anguli_Oris_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesDepressor_Labii_Inferioris_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesDepressor_Labii_Inferioris_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesDepressor_Septi_Nasi_uscle_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesDepressor_Supercilii_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesDepressor_Supercilii_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesDigastric_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesDigastric_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesFrontalis_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesFrontalis_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesHyoglossus_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesHyoglossus_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesLevator_Anguli_Oris_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesLevator_Anguli_Oris_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesLevator_Labii_Superioris_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesLevator_Labii_Superioris_Muscle_Left1_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesLevator_Labii_Superioris_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesLevator_Labii_Superioris_Muscle_Right1_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesLevator_Scapulae_Muscle_03_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesLevator_Scapulae_Muscle_03_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesMasseter_Deep_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesMasseter_Deep_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesMasseter_Superficial_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesMasseter_Superficial_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesMentalis_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesMentalis_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesMylohyoid_Muscle_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesNasal_Cartilage_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesNasalis_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesNasalis_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesOrbicularis_Oculi_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesOrbicularis_Oculi_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesOrbicularis_Oris_Muscle_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesPlatysma_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesPlatysma_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesPosterior_Auricular_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesPosterior_Auricular_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesProcerus_Muscle_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesProcerus_Muscle1_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesRisorius_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesRisorius_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesScalene_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesScalene_Muscle_Left1_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesScalene_Muscle_Left2_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesScalene_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesScalene_Muscle_Right1_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesScalene_Muscle_Right2_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesScalenus_Anterior_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesScalenus_Anterior_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSemispinalis_Capitis_Muscle_01_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSemispinalis_Capitis_Muscle_01_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSemispinalis_Capitis_Muscle_02_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSemispinalis_Capitis_Muscle_02_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSemispinalis_Capitis_Muscle_03_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSemispinalis_Capitis_Muscle_03_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSemispinalis_Capitis_Muscle_04_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSemispinalis_Capitis_Muscle_04_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSemispinalis_Capitis_Muscle_05_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSemispinalis_Capitis_Muscle_05_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSemispinalis_Capitis_Muscle_06_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSemispinalis_Capitis_Muscle_06_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSemispinalis_Cervicis_Muscle_01_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSemispinalis_Cervicis_Muscle_01_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSemispinalis_Cervicis_Muscle_02_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSemispinalis_Cervicis_Muscle_02_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSemispinalis_Cervicis_Muscle_03_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSemispinalis_Cervicis_Muscle_03_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSemispinalis_Cervicis_Muscle_04_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSemispinalis_Cervicis_Muscle_04_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSternocleidomastoid_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSternocleidomastoid_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSternohyoid_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSternohyoid_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSternothyroideus_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSternothyroideus_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesStylohyoid_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesStylohyoid_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSuperior_Auricular_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesSuperior_Auricular_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesTemporal_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesTemporal_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesThyrohyoid_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesThyrohyoid_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesZygomaticus_Major_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesZygomaticus_Major_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesZygomaticus_Minor_Muscle_Left_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Head_MusclesZygomaticus_Minor_Muscle_Right_MALE_F_1Muscle_Head_mat_0.geometry} material={materials.MALE_F_1Muscle_Head_mat} rotation={[Math.PI / 2, 0, 0]} />
            </group>
            <group position={[0, 1.331, -87.453]}>
              <mesh geometry={nodes.MALE_F_1Leg_MusclesAbductor_Digiti_Minimi_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesAbductor_Digiti_Minimi_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesAbductor_Hallucis_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesAbductor_Hallucis_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesAdductor_Brevis_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesAdductor_Brevis_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesAdductor_Longus_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesAdductor_Longus_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesAdductor_Magnus_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesAdductor_Magnus_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesBicep_Femoris_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesBicep_Femoris_Muscle_Left1_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesBicep_Femoris_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesBicep_Femoris_Muscle_Right1_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesBiceps_Femoris_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesBiceps_Femoris_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesExtensor_Digitorum_Longus_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesExtensor_Digitorum_Longus_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesExtensor_Hallucis_Brevis_Muscle_01_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesExtensor_Hallucis_Brevis_Muscle_01_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesExtensor_Hallucis_Brevis_Muscle_02_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesExtensor_Hallucis_Brevis_Muscle_02_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesExtensor_Hallucis_Brevis_Muscle_03_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesExtensor_Hallucis_Brevis_Muscle_03_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesExtensor_Hallucis_Brevis_Muscle_04_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesExtensor_Hallucis_Brevis_Muscle_04_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesExtensor_Hallucis_Longus_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesExtensor_Hallucis_Longus_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesFlexor_Digitorum_Brevis_Muscle_01_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesFlexor_Digitorum_Brevis_Muscle_01_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesFlexor_Digitorum_Brevis_Muscle_02_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesFlexor_Digitorum_Brevis_Muscle_02_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesFlexor_Digitorum_Brevis_Muscle_03_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesFlexor_Digitorum_Brevis_Muscle_04_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesFlexor_Digitorum_Longus_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesFlexor_Digitorum_Longus_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesFlexor_Hallucis_Longus_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesFlexor_Hallucis_Longus_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesGastrocnemius_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesGastrocnemius_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesGluteus_Maximus_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesGluteus_Maximus_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesGluteus_Medius_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesGluteus_Medius_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesGluteus_Minimus_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesGluteus_Minimus_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesGracilis_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesGracilis_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesIliacus_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesIliacus_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesInferior_Gemellus_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesInferior_Gemellus_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesLigamentum_Patella_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesLigamentum_Patella_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesObturator_Externus_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesObturator_Externus_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesObturator_Internus_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesObturator_Internus_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesPectineus_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesPectineus_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesPeroneus_Brevis_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesPeroneus_Brevis_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesPeroneus_longus_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesPeroneus_longus_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesPiriformis_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesPiriformis_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesPsoas_Major_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesPsoas_Major_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesQuadriceps_Femoris_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesQuadriceps_Femoris_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesRectus_Femoris_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesRectus_Femoris_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesSacrotuberous_Ligament_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesSacrotuberous_Ligament_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesSartorius_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesSartorius_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesSemimembranosus_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesSemimembranosus_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesSoleus_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesSoleus_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesSuperior_Gemellus_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesSuperior_Gemellus_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesTensor_Fasciae_Latae_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesTensor_Fasciae_Latae_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesTibialis_Anterior_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesTibialis_Anterior_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesTibialis_Posterior_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesTibialis_Posterior_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesVastus_Intermedius_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesVastus_Intermedius_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesVastus_Lateralis_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesVastus_Lateralis_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesVastus_Medialis_Muscle_Left_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
              <mesh geometry={nodes.MALE_F_1Leg_MusclesVastus_Medialis_Muscle_Right_MALE_F_1Muscle_Leg_mat_0.geometry} material={materials.MALE_F_1Muscle_Leg_mat} />
            </group>
            <group position={[0, 1.331, -87.453]}>
              <mesh geometry={nodes.MALE_F_1Torso_MusclesAbdominal_External_Oblique_Muscle_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesDiaphragm_Muscle_Geo_MALE_F_1Muscles_Diaphragm_Geo1_0.geometry} material={materials.MALE_F_1Muscles_Diaphragm_Geo1} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesIlcostal_Muscle_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesIlcostal_Muscle_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesInfraspinatus_Muscle_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesInfraspinatus_Muscle_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesIntercostal_Muscle_Large_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesIntercostal_Muscle_Large_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesIntercostal_Muscle_Small_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesIntercostal_Muscle_Small_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesInternal_Oblique_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesInternal_Oblique_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesLatissim_Muscle_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesLatissim_Muscle_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesLevator_Scapulae_Muscle_01_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesLevator_Scapulae_Muscle_01_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesLevator_Scapulae_Muscle_02_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesLevator_Scapulae_Muscle_02_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesLevator_Scapulae_Muscle_04_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesLevator_Scapulae_Muscle_04_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesLongissimus_Muscle_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesLongissimus_Muscle_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesOmohyoideus_Muscle_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesOmohyoideus_Muscle_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesPectoral_Muscle_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesPectoral_Muscle_right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesPectoralis_Minor_Muscle_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesPectoralis_Minor_Muscle_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesPsoas_Minor_Muscle_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesPsoas_Minor_Muscle_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesQuadratus_Lumborum_Muscle_01_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesQuadratus_Lumborum_Muscle_01_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesQuadratus_Lumborum_Muscle_02_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesQuadratus_Lumborum_Muscle_02_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesRectus_Abdominis_Muscle_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesRhomboid_Major_Muscle_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesRhomboid_Major_Muscle_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesRhomboid_Minor_Muscle_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesRhomboid_Minor_Muscle_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesScalenus_Anterior_Muscle_Left2_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesScalenus_Anterior_Muscle_Left3_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesScalenus_Anterior_Muscle_Right1_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesScalenus_Anterior_Muscle_Right2_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesScalenus_Posterior_Muscle_01_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesScalenus_Posterior_Muscle_01_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesScalenus_Posterior_Muscle_02_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesScalenus_Posterior_Muscle_02_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesScalenus_Posterior_Muscle_03_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesScalenus_Posterior_Muscle_03_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSerratus_Anterior_Muscle_01_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSerratus_Anterior_Muscle_01_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSerratus_Anterior_Muscle_02_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSerratus_Anterior_Muscle_02_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSerratus_Anterior_Muscle_03_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSerratus_Anterior_Muscle_03_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSerratus_Anterior_Muscle_04_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSerratus_Anterior_Muscle_04_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSerratus_Anterior_Muscle_05_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSerratus_Anterior_Muscle_05_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSerratus_Anterior_Muscle_06_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSerratus_Anterior_Muscle_06_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSerratus_Anterior_Muscle_07_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSerratus_Anterior_Muscle_07_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSerratus_Anterior_Muscle_08_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSerratus_Anterior_Muscle_08_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSerratus_Anterior_Muscle_09_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSerratus_Anterior_Muscle_09_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSpinalis_Muscle_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSpinalis_Muscle_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSplenius_Capitus_Muscle_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSplenius_Capitus_Muscle_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSplenius_Cervicis_Muscle_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSplenius_Cervicis_Muscle_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSubscapularis_Muscle_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSubscapularis_Muscle_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSupraspinatus_Muscle_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesSupraspinatus_Muscle_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesTeres_Major_Muscle_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesTeres_Major_Muscle_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesTeres_Minor_Muscle_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesTeres_Minor_Muscle_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesTransversus_Abdominis_Muscle_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesTrapezius_Muscle_Left_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
              <mesh geometry={nodes.MALE_F_1Torso_MusclesTrapezius_Muscle_Right_MALE_F_1Muscle_Torso_mat_0.geometry} material={materials.MALE_F_1Muscle_Torso_mat} rotation={[Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Muscles;