/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Nervous.gltf 
Author: issamchong (https://sketchfab.com/issamchong)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nervous-7fb38c716d1c446eb296cb38a2f55963
Title: Nervous
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Nervous(props) {
  const { nodes, materials } = useGLTF('/Nervous.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.MALE_F_1Nervous_Eye_Ball_Inner_Left_GeoSG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.MALE_F_1Nervous_Eye_Ball_Outer_Left_GeoSG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.MALE_F_1Nervous_Nerves_Left_GeoSG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.MALE_F_1Nervous_Nerves_Left_GeoSG} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.MALE_F_1Nervous_Nerves_Left_GeoSG} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.MALE_F_1Nervous_Nerves_Left_GeoSG} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.MALE_F_1Nervous_Nerves_Left_GeoSG} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.MALE_F_1Nervous_Nerves_Left_GeoSG} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.MALE_F_1Nervous_Nerves_Left_GeoSG} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.MALE_F_1Nervous_Nerves_Left_GeoSG} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.MALE_F_1Nervous_Nerves_Left_GeoSG} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.MALE_F_1Nervous_Nerves_Left_GeoSG} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.MALE_F_1Nervous_Nerves_Left_GeoSG} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.MALE_F_1Nervous_Nerves_Left_GeoSG} />
      </group>
    </group>
  )
}

export default Nervous;