/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Pancreas.gltf 
Author: funnyeducomics (https://sketchfab.com/funnyeducomics)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/pancreas-93cda9cac5224e12857909099e39b773
Title: Pancreas
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pancreas(props) {
  const { nodes, materials } = useGLTF('/Pancreas.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.MALE_F_1Endocrine_Pancreas_GeoSG} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

export default Pancreas;