/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Respiratory.gltf 
Author: issamchong (https://sketchfab.com/issamchong)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/smoothed-version-fd275bde49dc454480c69edb2c283f1c
Title: smoothed_version
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Respiratory(props) {
  const { nodes, materials } = useGLTF('/Respiratory.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.MALE_F_1Respiratoy_Diaphragm_GeoSG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.MALE_F_1Respiratoy_Thyroid_Membrane_GeoSG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.MALE_F_1Respiratory_Cricothyroid_Ligament_GeoSG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.MALE_F_1Respiratoy_Bronchi_Geo_RightSG} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.MALE_F_1Respiratoy_Bronchi_Geo_RightSG} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.MALE_F_1Respiratoy_Bronchi_Geo_RightSG} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.MALE_F_1Respiratoy_Bronchi_Geo_RightSG} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.MALE_F_1Respiratoy_Bronchi_Geo_RightSG} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.MALE_F_1Respiratoy_Bronchi_Geo_RightSG} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.MALE_F_1Respiratoy_Lung_Geo_RightSG} />
      </group>
    </group>
  )
}

export default Respiratory;