/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Urinary.gltf 
Author: issamchong (https://sketchfab.com/issamchong)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/urinary-7c4ef3b59298420cb8fb6596e54ed758
Title: Urinary
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Urinary.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.MALE_F_1Male_Endocrine_Pancreas_GeoSG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.MALE_F_1Male_Endocrine_Thymus_Gland_GeoSG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.MALE_F_1Male_Endocrine_Thyroid_Gland_GeoSG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.MALE_F_1Male_Reproductive_Corpora_Cavernosa_GeoSG} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.MALE_F_1Male_Reproductive_Corpus_Spongiosum_GeoSG} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.MALE_F_1Male_Reproductive_Prostate_GeoSG} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.MALE_F_1Male_Urinary_Bladder_GeoSG} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.MALE_F_1Male_Circulatory_Urinary_Arteries_GeoSG} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.MALE_F_1Male_Circulatory_Urinary_Arteries_GeoSG} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.MALE_F_1Male_Circulatory_Urinary_Veins_GeoSG} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.MALE_F_1Male_Circulatory_Urinary_Veins_GeoSG} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.MALE_F_1Male_Endocrine_Adrenal_Gland_Geo_LeftSG} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.MALE_F_1Male_Reproductive_Ductus_Deferens_Geo_LeftSG} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.MALE_F_1Male_Reproductive_Testis_Geo_LeftSG} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.MALE_F_1Male_Urinary_Kidney_Geo_LeftSG} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.MALE_F_1Male_Urinary_Ureter_Geo_LeftSG} />
      </group>
    </group>
  )
}

useGLTF.preload('/Urinary.gltf')
